### ISSUE TITLE
"Loot Received, Wishlists, Prios, and Notes" from TMB freezes game for approx 15 seconds

### ISSUE THREAD

**Issue by papa-smurf** [mwonng/TMBLoot#1]
Is there any specific reason for having to import ALL of the data from TMB? You only seem to use the item name and player name at this point and even then you only read the wishlist lines and ignore the rest (received/item_note)?

Pasting the data in /ts show freezes the game for about 15 seconds for me (which can be troublesome during raids I imagine). Also, after you click the "Save" button to import, the original CSV is not gone, meaning that every time you execute /ts show from that point on it freezes your game again.

This addon generates a lot of overhead (performance-wise) for what it does. Why keep a full copy of the csv the player imported in the savedvariables for example?

All in all a good first attempt and it's good to see more content creators! At this point I wouldn't feel comfortable recommending this to others as-is, and I would expect a alpha/beta flag in curseforge at the bare minimum so people can test it out and provide feedback without shooting it down completely :)

Also I noticed that you potentially mention the same player name multiple times without mentioning the order in which the item is positioned on their wishlist, so I'm not too sure what to do with the announced info atm?

![image](https://user-images.githubusercontent.com/4224975/125630520-3a45d84c-9a7c-4a57-974e-d3f9ca2c47e3.png)

**Comment by mwonng** [comment]
yeah can import wish list only or priority only, I notice the whole thing looks bigger, for my usage, I prefer have a wishlist + prios list only.

btw, can you post your file so I can test duplicated player names. currently, it counting by all rows from csv, so will iteration all and build a table in Lua for `wishlist` and `prio`, everytime it found the same item it will add the user's name.

I will mark the next fix as a beta to avoid more downloads. thanks for advice

**Comment by mwonng** [comment]
this has been updated in the the new version, https://github.com/mwonng/TMBLoot/releases/tag/v0.1.3
